### ISSUE TITLE
Error reading IBAQ file

### ISSUE THREAD

**Issue by ypriverol** [bigbio/qpx#26]
```
Traceback (most recent call last):
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/bin/quantmsio_cli", line 33, in <module>
    sys.exit(load_entry_point('quantmsio==0.0.3', 'console_scripts', 'quantmsio_cli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/quantmsio-0.0.3-py3.11.egg/quantms_io/quantmsio_cli.py", line 58, in quantms_io_main
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/quantmsio-0.0.3-py3.11.egg/quantms_io/commands/statistics.py", line 51, in feature_file_statistics
    ---------------------------------
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/quantmsio-0.0.3-py3.11.egg/quantms_io/commands/statistics.py", line 41, in write_absolute_stats
    
  File "/hps/software/users/juan/pride/anaconda3/envs/quantmsio/lib/python3.11/site-packages/quantmsio-0.0.3-py3.11.egg/quantms_io/core/statistics.py", line 43, in get_number_of_samples
    2.8333333333...
                ^^^^
ValueError: No SampleID column found in the ibaq file

```

**Comment by Shen-YuFei** [comment]
Fixed by [365db393](https://github.com/bigbio/qpx/commit/365db393f3b6bee989b9121f0af229756bbbcdb9).

`get_number_of_samples()` now falls back to `sample_accession` when an iBAQ table does not contain `SampleID`, which directly addresses the reported error. The fix is included in the 0.0.3 and v1.0.x releases.

Closing as fixed.
